import os
import sys
import markdown
from xhtml2pdf import pisa
from crewai import Agent, Task, Crew, Process
from crewai.tools import BaseTool
from crewai_tools import SerperDevTool
from pydantic import BaseModel, Field
from typing import Type
from dotenv import load_dotenv

load_dotenv()

class PDFGeneratorInput(BaseModel):
    """Input schema for PDFGeneratorTool."""
    output_filename: str = Field(..., description="The final PDF filename (e.g., 'lite_output/final_report.pdf').")

class PDFGeneratorTool(BaseTool):
    name: str = "Generate PDF Report"
    description: str = "Reads the generated MD files (spec, tech, code) and compiles them into a PDF."
    args_schema: Type[BaseModel] = PDFGeneratorInput

    def _run(self, output_filename: str) -> str:
        try:
            os.makedirs(os.path.dirname(output_filename), exist_ok=True)
            
            # 定義 CSS: 關鍵是 pre 的 white-space 和 font-family
            css_style = """
            <style>
                @page { size: A4; margin: 2cm; }
                body { font-family: Helvetica, sans-serif; font-size: 10pt; line-height: 1.5; color: #333; }
                
                h1 { color: #2c3e50; border-bottom: 2px solid #2c3e50; padding-bottom: 10px; margin-top: 30px; }
                h2 { color: #e67e22; margin-top: 25px; border-bottom: 1px solid #eee; }
                h3 { color: #34495e; margin-top: 20px; }
                
                /* [關鍵修正] 程式碼區塊樣式 */
                pre { 
                    background-color: #f8f9fa; 
                    border: 1px solid #e9ecef; 
                    border-radius: 4px;
                    padding: 10px; 
                    font-family: Courier, monospace; /* 必須用等寬字型 */
                    font-size: 9pt;
                    white-space: pre-wrap; /* [重要] 保留換行符號 */
                    word-wrap: break-word; /* 避免過長不換行 */
                }
                code { 
                    font-family: Courier, monospace; 
                    color: #d63384; 
                }
                p { margin-bottom: 10px; }
            </style>
            """
            
            combined_content = "# Project Final Report\n\nGenerated by SaaS Launchpad Crew\n\n"
            
            # 1. 處理 Spec (通常是純 Markdown，直接讀)
            if os.path.exists("lite_output/1_spec.md"):
                with open("lite_output/1_spec.md", "r", encoding="utf-8") as f:
                    combined_content += f"\n\n---\n\n{f.read()}"

            # 2. 處理 Tech Stack (通常是純 Markdown，直接讀)
            if os.path.exists("lite_output/2_tech_stack.md"):
                with open("lite_output/2_tech_stack.md", "r", encoding="utf-8") as f:
                    combined_content += f"\n\n---\n\n{f.read()}"

            # 3. [關鍵修正] 處理 Code Skeleton - 防呆邏輯
            code_path = "lite_output/3_mvp_skeleton.md"
            if os.path.exists(code_path):
                with open(code_path, "r", encoding="utf-8") as f:
                    raw_code = f.read().strip()
                    
                # 檢查是否已經包含 markdown code block 標記
                if not raw_code.startswith("```"):
                    # 如果沒有，我們手動加上去，強制格式化
                    formatted_code = f"\n# Phase 3: MVP Skeleton Code\n\n```python\n{raw_code}\n```"
                else:
                    # 如果已經有，就直接用
                    formatted_code = f"\n\n---\n\n{raw_code}"
                
                combined_content += formatted_code

            # 轉換 Markdown -> HTML -> PDF
            html_content = markdown.markdown(combined_content, extensions=['fenced_code', 'codehilite'])
            full_html = f"<html><head>{css_style}</head><body>{html_content}</body></html>"

            with open(output_filename, "wb") as pdf_file:
                pisa_status = pisa.CreatePDF(full_html, dest=pdf_file)

            if pisa_status.err:
                return f"Error creating PDF: {pisa_status.err}"
            
            # 清理中間產物 (Optional)
            files_to_clean = ["lite_output/1_spec.md", "lite_output/2_tech_stack.md", "lite_output/3_mvp_skeleton.md"]
            for fpath in files_to_clean:
                if os.path.exists(fpath):
                    try:
                        os.remove(fpath)
                    except OSError as e:
                        print(f"Warning: Could not remove temp file {fpath}: {e}")

            return f"Successfully compiled PDF report at: {output_filename}"
            
        except Exception as e:
            return f"Exception during PDF creation: {str(e)}"

# --- Main Crew Logic ---

def run_lite_crew(inputs=None):
    print("=== Initializing SaaS Launchpad Crew (Lite Version) ===")
    
    search_tool = SerperDevTool()
    pdf_tool = PDFGeneratorTool()

    # --- Agents ---
    
    analyst = Agent(
        role='Lead Product Analyst',
        goal='Analyze the user idea and produce a clear PRD.',
        backstory="Expert at translating vague ideas into logical docs.",
        tools=[search_tool],
        verbose=False,
        memory=True
    )

    resource_hunter = Agent(
        role='Tech Resource Scout',
        goal='Find suitable Python libraries and APIs.',
        backstory="Familiar with Python ecosystem.",
        tools=[search_tool],
        verbose=False,
        memory=True
    )

    architect = Agent(
        role='Senior Technical Architect',
        goal='Produce the MVP code structure and compile the PDF.',
        backstory="Excels at building functional MVPs.",
        tools=[pdf_tool], 
        verbose=False,
        memory=True
    )

    # --- Tasks ---
    
    # Task 1
    task_analysis = Task(
        description=(
            "Analyze the user's idea: '{task}'.\n"
            "Define features, risks, and competitors."
        ),
        expected_output="A Markdown document containing the analysis.",
        agent=analyst,
        output_file="lite_output/1_spec.md" 
    )

    # Task 2
    task_resources = Task(
        description=(
            "Recommend tech stack based on the spec."
        ),
        expected_output="A Markdown list of tools and APIs.",
        agent=resource_hunter,
        output_file="lite_output/2_tech_stack.md"
    )

    # Task 3
    task_coding = Task(
        description=(
            "Write the core 'main.py' skeleton code.\n"
            "Wrap the python code in markdown code blocks (```python ... ```)."
        ),
        expected_output="Python code skeleton in Markdown format.",
        agent=architect,
        output_file="lite_output/3_mvp_skeleton.md"
    )

    # Task 4
    task_report = Task(
        description=(
            "The previous tasks have already saved the files.\n"
            "You just need to call the 'Generate PDF Report' tool.\n"
            "Set output_filename to 'lite_output/final_report.pdf'.\n"
            "In your final answer, just say 'DONE' and nothing else."
        ),
        expected_output="The word 'DONE'.",
        agent=architect
    )

    # --- Crew ---
    crew = Crew(
        agents=[analyst, resource_hunter, architect],
        tasks=[task_analysis, task_resources, task_coding, task_report],
        process=Process.sequential,
        verbose=False
    )

    return crew

if __name__ == "__main__":
    # Local Testing Logic
    print("## Local Testing Mode ##")
    user_idea = input("\nPlease enter your project idea: ")
    if not user_idea: sys.exit()
    
    my_crew = run_lite_crew()
    test_inputs = {"task": user_idea}
    
    print(f"\n[System] Kicking off crew...\n")
    result = my_crew.kickoff(inputs=test_inputs)
    print("\n[Done] Check the lite_output folder.")