import os
import sys
import html  # [新增] 用於轉義 HTML 特殊字符
import markdown
from xhtml2pdf import pisa
from crewai import Agent, Task, Crew, Process
from crewai.tools import BaseTool
from crewai_tools import SerperDevTool
from pydantic import BaseModel, Field
from typing import Type
from dotenv import load_dotenv

load_dotenv()

class PDFGeneratorInput(BaseModel):
    """Input schema for PDFGeneratorTool."""
    output_filename: str = Field(..., description="The final PDF filename.")

class PDFGeneratorTool(BaseTool):
    name: str = "Generate PDF Report"
    description: str = "Compiles generated files into a PDF report."
    args_schema: Type[BaseModel] = PDFGeneratorInput

    def _run(self, output_filename: str) -> str:
        try:
            os.makedirs(os.path.dirname(output_filename), exist_ok=True)
            
            # --- CSS 樣式 (針對 xhtml2pdf 優化) ---
            css_style = """
            <style>
                @page { size: A4; margin: 2cm; }
                body { font-family: Helvetica, sans-serif; font-size: 10pt; line-height: 1.6; color: #333; }
                h1 { color: #2c3e50; border-bottom: 2px solid #2c3e50; padding-bottom: 10px; margin-top: 30px; }
                h2 { color: #e67e22; margin-top: 25px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
                
                /* [關鍵] 強制保留換行與格式的程式碼區塊樣式 */
                pre {
                    font-family: "Courier New", Courier, monospace;
                    font-size: 9pt;
                    background-color: #f5f7f9;
                    border: 1px solid #e1e4e8;
                    border-radius: 5px;
                    padding: 15px;
                    margin: 20px 0;
                    white-space: pre-wrap; /* 必須：保留換行 */
                    word-wrap: break-word; /* 必須：長行自動換行 */
                }
            </style>
            """
            
            # --- 1. 處理 Markdown 文件部分 (Spec & Tech Stack) ---
            md_content = "# Project Final Report\n\nGenerated by SaaS Launchpad Crew\n\n"
            
            files_to_merge_md = [
                "lite_output/1_spec.md",
                "lite_output/2_tech_stack.md"
            ]
            
            for fpath in files_to_merge_md:
                if os.path.exists(fpath):
                    with open(fpath, "r", encoding="utf-8") as f:
                        md_content += f"\n\n---\n\n{f.read()}"

            # 將 Markdown 轉為 HTML
            report_html = markdown.markdown(md_content, extensions=['fenced_code', 'codehilite'])
            
            # --- 2. [關鍵修改] 處理程式碼部分 (Raw Python) ---
            # 我們不再依賴 Markdown 解析器，而是手動封裝 HTML
            code_path = "lite_output/3_mvp_skeleton.md"
            code_html = ""
            
            if os.path.exists(code_path):
                with open(code_path, "r", encoding="utf-8") as f:
                    raw_code = f.read().strip()
                
                # 清理 Agent 可能多加的 markdown 標記 (```python ... ```)
                # 這樣我們才能拿到乾淨的 raw code
                if raw_code.startswith("```"):
                    lines = raw_code.split('\n')
                    # 去掉第一行 (```python) 和最後一行 (```)
                    if len(lines) > 2:
                        raw_code = "\n".join(lines[1:-1])
                
                # [核心邏輯] 手動轉義並包裹 <pre>
                # html.escape 會把 <, >, & 轉成安全字符，避免破壞 HTML 結構
                safe_code = html.escape(raw_code)
                code_html = f"""
                <div class="code-section">
                    <h2>Phase 3: MVP Skeleton Code</h2>
                    <pre>{safe_code}</pre>
                </div>
                """

            # --- 3. 組合最終 HTML ---
            full_html = f"<html><head>{css_style}</head><body>{report_html}{code_html}</body></html>"

            # 生成 PDF
            with open(output_filename, "wb") as pdf_file:
                pisa_status = pisa.CreatePDF(full_html, dest=pdf_file)

            if pisa_status.err:
                return f"Error creating PDF: {pisa_status.err}"
            
            # 清理檔案
            all_files = files_to_merge_md + [code_path]
            for fpath in all_files:
                if os.path.exists(fpath):
                    try:
                        os.remove(fpath)
                    except:
                        pass

            return f"Successfully compiled PDF report at: {output_filename}"
            
        except Exception as e:
            return f"Exception during PDF creation: {str(e)}"

# --- Main Crew Logic ---

def run_lite_crew(inputs=None):
    print("=== Initializing SaaS Launchpad Crew (Lite Version) ===")
    
    search_tool = SerperDevTool()
    pdf_tool = PDFGeneratorTool()

    # --- Agents ---
    
    analyst = Agent(
        role='Lead Product Analyst',
        goal='Analyze the user idea and produce a clear PRD.',
        backstory="Expert at translating vague ideas into logical docs.",
        tools=[search_tool],
        verbose=False,
        memory=True
    )

    resource_hunter = Agent(
        role='Tech Resource Scout',
        goal='Find suitable Python libraries and APIs.',
        backstory="Familiar with Python ecosystem.",
        tools=[search_tool],
        verbose=False,
        memory=True
    )

    architect = Agent(
        role='Senior Technical Architect',
        goal='Produce the MVP code structure and compile the PDF.',
        backstory="Excels at building functional MVPs.",
        tools=[pdf_tool], 
        verbose=False,
        memory=True
    )

    # --- Tasks ---
    
    task_analysis = Task(
        description=(
            "Analyze the user's idea: '{task}'.\n"
            "Define features, risks, and competitors."
        ),
        expected_output="A Markdown document containing the analysis.",
        agent=analyst,
        output_file="lite_output/1_spec.md" 
    )

    task_resources = Task(
        description=(
            "Recommend tech stack based on the spec."
        ),
        expected_output="A Markdown list of tools and APIs.",
        agent=resource_hunter,
        output_file="lite_output/2_tech_stack.md"
    )

    # [Task 修改] 讓 Agent 輸出純 Markdown Code Block 即可，我們在 Tool 裡會負責剝殼
    task_coding = Task(
        description=(
            "Write the core 'main.py' skeleton code.\n"
            "Output the code inside a markdown code block: ```python ... ```\n"
            "Do not add any other text outside the code block."
        ),
        expected_output="Python code skeleton.",
        agent=architect,
        output_file="lite_output/3_mvp_skeleton.md"
    )

    task_report = Task(
        description=(
            "The previous tasks have already saved the files.\n"
            "Call the 'Generate PDF Report' tool.\n"
            "Set output_filename to 'lite_output/final_report.pdf'.\n"
            "In your final answer, just say 'DONE' and nothing else."
        ),
        expected_output="The word 'DONE'.",
        agent=architect
    )

    # --- Crew ---
    crew = Crew(
        agents=[analyst, resource_hunter, architect],
        tasks=[task_analysis, task_resources, task_coding, task_report],
        process=Process.sequential,
        verbose=False
    )

    return crew

if __name__ == "__main__":
    # Local Testing Logic
    print("## Local Testing Mode ##")
    user_idea = input("\nPlease enter your project idea: ")
    if not user_idea: sys.exit()
    
    my_crew = run_lite_crew()
    test_inputs = {"task": user_idea}
    
    print(f"\n[System] Kicking off crew...\n")
    result = my_crew.kickoff(inputs=test_inputs)
    print("\n[Done] Check the lite_output folder.")