import os
import sys
import html
import re
import markdown
from xhtml2pdf import pisa
from crewai import Agent, Task, Crew, Process
from crewai.tools import BaseTool
from crewai_tools import SerperDevTool
from pydantic import BaseModel, Field
from typing import Type
from dotenv import load_dotenv

load_dotenv()

class PDFGeneratorInput(BaseModel):
    output_filename: str = Field(..., description="The final PDF filename.")

class PDFGeneratorTool(BaseTool):
    name: str = "Generate PDF Report"
    description: str = "Compiles generated files into a PDF report."
    args_schema: Type[BaseModel] = PDFGeneratorInput

    def _clean_markdown_text(self, text: str) -> str:
        """
        核彈級清洗：
        1. 移除每一行開頭的所有縮排 (解決標題變純文字的問題)。
        2. 確保標題(#)和列表(-)前面有換行。
        """
        lines = text.split('\n')
        cleaned_lines = []
        
        for line in lines:
            # 1. 強制移除行首縮排 (這步最關鍵！)
            # 如果不這樣做，Markdown 解析器會把縮排的文字當成 <pre> 程式碼
            stripped = line.lstrip() 
            cleaned_lines.append(stripped)
            
        cleaned_text = "\n".join(cleaned_lines)

        # 2. Regex 補強：確保 Header 前面有兩個換行 (Markdown 標準)
        # 把 "任意文字# Title" 變成 "任意文字\n\n# Title"
        cleaned_text = re.sub(r'(?<!\n)#', '\n\n#', cleaned_text)
        
        # 3. Regex 補強：確保列表 Item 前面有換行
        # 把 "任意文字- Item" 變成 "任意文字\n- Item"
        cleaned_text = re.sub(r'(?<!\n)- ', '\n- ', cleaned_text)
        cleaned_text = re.sub(r'(?<!\n)\* ', '\n* ', cleaned_text)
        
        return cleaned_text

    def _run(self, output_filename: str) -> str:
        try:
            os.makedirs(os.path.dirname(output_filename), exist_ok=True)
            
            # --- CSS 設定 ---
            # 重點：加入 strong/b 標籤的字型權重，確保 xhtml2pdf 真的會渲染粗體
            css_style = """
            <style>
                @page {
                    size: A4;
                    margin: 2cm;
                    @frame footer_frame {
                        -pdf-frame-content: footerContent;
                        bottom: 1cm;
                        margin-left: 2cm;
                        margin-right: 2cm;
                        height: 1cm;
                    }
                }
                
                body { 
                    font-family: Helvetica, sans-serif; 
                    font-size: 10pt; 
                    line-height: 1.4; 
                    color: #333; 
                }
                
                /* 標題樣式 */
                h1 { 
                    color: #2c3e50; 
                    border-bottom: 2px solid #2c3e50; 
                    padding-bottom: 5px; 
                    margin-top: 20px; 
                    margin-bottom: 15px; 
                    font-size: 18pt; 
                    font-weight: bold;
                }
                
                h2 { 
                    color: #e67e22; 
                    margin-top: 15px; 
                    margin-bottom: 10px; 
                    border-bottom: 1px solid #eee; 
                    font-size: 14pt; 
                    font-weight: bold;
                }
                
                /* 確保粗體真的會變粗 */
                strong, b { font-weight: bold; color: #000; }
                
                /* 列表緊湊化 */
                ul { margin-bottom: 10px; padding-left: 15px; }
                li { margin-bottom: 3px; }
                
                /* 段落間距 */
                p { margin-bottom: 8px; text-align: justify; }

                /* 程式碼區塊 (深色背景) */
                .code-box {
                    font-family: Courier;
                    font-size: 9pt;
                    background-color: #282c34;
                    color: #ffffff;
                    border: 1px solid #ddd;
                    padding: 10px;
                    margin-top: 10px;
                    line-height: 1.2;
                    border-radius: 4px;
                    white-space: pre-wrap; /* 允許換行 */
                }
            </style>
            """
            
            html_parts = []
            html_parts.append(f"<html><head>{css_style}</head><body>")
            html_parts.append('<div id="footerContent" style="text-align:center; font-size:9pt; color:#777;">Page <pdf:pagenumber></div>')
            
            html_parts.append("<h1>Project Final Report</h1><p>Generated by SaaS Launchpad Crew</p>")
            html_parts.append("<hr>")

            # --- 1. 處理 Markdown (Spec & Tech Stack) ---
            file_map = [
                ("lite_output/1_spec.md", "Phase 1: Product Specification"),
                ("lite_output/2_tech_stack.md", "Phase 2: Tech Stack")
            ]

            for filepath, section_title in file_map:
                if os.path.exists(filepath):
                    with open(filepath, "r", encoding="utf-8") as f:
                        raw_content = f.read()

                    # [核心步驟] 呼叫清洗函數
                    # 這一條會移除所有行首空格，讓 Markdown Parser 終於能看懂 "#" 是標題
                    clean_content = self._clean_markdown_text(raw_content)

                    # 轉換 HTML
                    # extensions=['extra'] 支援表格等語法
                    # 注意：移除了 'nl2br'，因為它會導致段落間距過大。
                    # 如果 Agent 有正確分段(空一行)，Markdown 自己會處理 p 標籤。
                    html_content = markdown.markdown(clean_content, extensions=['extra', 'sane_lists'])

                    html_parts.append(f"<h2>{section_title}</h2>")
                    html_parts.append(html_content)
                    html_parts.append("<pdf:nextpage />")

            # --- 2. 處理程式碼 (Phase 3) ---
            code_path = "lite_output/3_mvp_skeleton.md"
            if os.path.exists(code_path):
                with open(code_path, "r", encoding="utf-8") as f:
                    raw_code = f.read().strip()
                
                # 去除頭尾的 ```
                if raw_code.startswith("```"):
                    lines = raw_code.split('\n')
                    if len(lines) >= 2: raw_code = "\n".join(lines[1:-1])

                safe_code = html.escape(raw_code)
                # 暴力換行法保留
                formatted_code = safe_code.replace("\n", "<br/>").replace(" ", "&nbsp;")
                
                html_parts.append("<h2>Phase 3: MVP Skeleton Code</h2>")
                html_parts.append(f'<div class="code-box">{formatted_code}</div>')

            html_parts.append("</body></html>")
            full_html = "".join(html_parts)
            
            # (可選) Debug 用：把中間產生的 HTML 存下來看
            # with open("debug.html", "w", encoding="utf-8") as f: f.write(full_html)

            with open(output_filename, "wb") as pdf_file:
                pisa_status = pisa.CreatePDF(full_html, dest=pdf_file)

            if pisa_status.err:
                return f"Error creating PDF: {pisa_status.err}"

            # 清理檔案
            for f in ["lite_output/1_spec.md", "lite_output/2_tech_stack.md", "lite_output/3_mvp_skeleton.md"]:
                if os.path.exists(f): os.remove(f)

            return f"Successfully compiled PDF report at: {output_filename}"
            
        except Exception as e:
            return f"Exception during PDF creation: {str(e)}"

# --- Main Crew Logic (不變) ---

def run_lite_crew(inputs=None):
    print("=== Initializing SaaS Launchpad Crew (Nuclear Text Cleaning) ===")
    
    search_tool = SerperDevTool()
    pdf_tool = PDFGeneratorTool()

    # Agents (設定不變)
    analyst = Agent(
        role='Lead Product Analyst',
        goal='Analyze the user idea and produce a clear PRD.',
        backstory="Expert at translating vague ideas into logical docs.",
        tools=[search_tool],
        verbose=False,
        memory=True
    )

    resource_hunter = Agent(
        role='Tech Resource Scout',
        goal='Find suitable Python libraries and APIs.',
        backstory="Familiar with Python ecosystem.",
        tools=[search_tool],
        verbose=False,
        memory=True
    )

    architect = Agent(
        role='Senior Technical Architect',
        goal='Produce the MVP code structure.',
        backstory="Excels at building functional MVPs.",
        tools=[pdf_tool], 
        verbose=False,
        memory=True
    )

    # Tasks (設定不變)
    task_analysis = Task(
        description=("Analyze the user's idea: '{task}'. Define features, risks, and competitors."),
        expected_output="A Markdown document containing the analysis. Use headers (#, ##).",
        agent=analyst,
        output_file="lite_output/1_spec.md" 
    )

    task_resources = Task(
        description=("Recommend tech stack based on the spec."),
        expected_output="A Markdown list of tools and APIs.",
        agent=resource_hunter,
        output_file="lite_output/2_tech_stack.md"
    )

    task_coding = Task(
        description=("Write the core 'main.py' skeleton code. Output ONLY raw code."),
        expected_output="Raw Python code text.",
        agent=architect,
        output_file="lite_output/3_mvp_skeleton.md"
    )

    task_report = Task(
        description=("Call 'Generate PDF Report' tool with output_filename='lite_output/final_report.pdf'. Return 'DONE'."),
        expected_output="The word 'DONE'.",
        agent=architect
    )

    crew = Crew(
        agents=[analyst, resource_hunter, architect],
        tasks=[task_analysis, task_resources, task_coding, task_report],
        process=Process.sequential,
        verbose=False
    )

    return crew

if __name__ == "__main__":
    print("## Local Testing Mode ##")
    user_idea = input("\nPlease enter your project idea: ")
    if not user_idea: sys.exit()
    my_crew = run_lite_crew()
    result = my_crew.kickoff(inputs={"task": user_idea})
    print("\n[Done] Check the lite_output folder.")